[project]
name = "cliiif"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chafa-py>=1.2.0",
    "textual>=8.2.8",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[project.scripts]
cliiif = "cliiif.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
